### ISSUE TITLE
Any clues on why this isn't working on my machine?

### ISSUE THREAD

**Issue by mrtgrizzly** [w0lfschild/colorfulSidebar_9#5]
Greetings,
Using brand new iMac running Mac OS Sierra.
Should colorfulSidebar work, as well as CosyTabs for Safari on this machine?
I had them working on my older iMac running OS X 10.8.5, using EasySIMBL.

I have downloaded mySIMBL.app, as well as the current plugins, and I am able to open mySIMBL.app and add the plugins to its window.  However, nothing is happening.  I have restarted the finder and restarted the machine, and still – nada.  I used to have EasySIMBL on this machine, but have now trashed it.  In fact, this whole machine was a migration from an earlier Mac. Not sure if there's something lingering somewhere that's conflicting that I need to trash?

One error message appears when I open mySIMBL.app:  it says:  "SIMBL Manager has determined that SIMBL is not installed or outdated on your system.  This means that applications and plugins which require SIMBL to function will likely not work."

What exactly might I do next ?  If I hit the "Install" button, I just get another error essentially saying, "sorry Charlie."

Thanks in advance.

<img width="345" alt="requires-simbl" src="https://user-images.githubusercontent.com/33304128/32307821-d110f716-bf58-11e7-919e-7ade3cc031fa.png">

**Comment by nico-147** [comment]
Hi grizzly,

I had that too, and had to first disable System Integrity Protection, then reinstall colorfulsidebar9 (v1.5.0 at the time of writing), then restart... and voila, it works. Basically, it's a protection Apple has created that protects your computer... but that also locks it from any improvement such as this delightful colored sidebar. Read more here about the good & bad side of this SIP ':
[https://en.wikipedia.org/wiki/System_Integrity_Protection]

Of course, you may re-enable System protection afterwards.

It may seem freaky, it's in fact very easy, and the only harm you do is enabling this developer to install one piece of utility inside the system. A bit over 2 years ago, you could have done it straight away because SIP didn't exist then.


To do this, restart in recovery mode and disable it in terminal - here are the detailed steps ':

1. Restart in Recovery mode holding cmd-r
2. Be patient - restart is longer than usual in that mode
3. Once you're in recovery mode, select "Terminal" from the utilities menu.
4. In terminal, type "csrutil disable".
5. You get a confirmation System Integrity has been disabled. 
6. Restart
7. Install colorfulsidebar9
8. Restart
9. Verify it works
10. Restart in Recovery Mode
11. Select "Terminal" from Utilities menu
12. In terminal, type "csrutil enable".
13. You get a confirmation it was reenabled
14. Restart

Voilà.

Tip : upon restart, you may have to wait for a minute or so, and re-open a new finder window to see the colors appear - ie the first finder window that opens up may still be all grey - seems simbl and its modules only load afterwards

**Comment by mrtgrizzly** [comment]
Greetings, and thanks for coming to the rescue with this suggestion.

I will give it a try. 

_**One question:**_  

Regarding the mySIMBL.app, should I just **only** have that app in my application folder and only have that installed, or should I also have SIMBL or easySIMBL ?

On my previous machine running OSX 10.8.5, I was using easySIMBL, but with this new machine running Sierra, I ditched other SIMBL apps and just installed mySIMBL.app.  Is that the way to go?

Thanks !

**Comment by nico-147** [comment]
I had the same question than you... I think the correct answer is : only
mysimbl is necessary. On my machine, both are installed though - and since
it works I don't wanna touch it anymore. Give it a try and keep us updated
please

----------
Nicolas de Biolley
http://www.nicolasdebiolley.net - Tél: +32.475.34.44.24
" I find hope in the darkest of days, and focus in the brightest. I do not
judge the universe" - Dalaï Lama
----------

**Comment by mrtgrizzly** [comment]
Thanks.  Yes, I understand about not wanting to touch anything if it happens to be working !

**Comment by w0lfschild** [comment]
@mrtgrizzly easySIMBL is dead and doesn't work on anything modern 10.9.5 +

mySIMBL should be all that's needed for SIMBL plugins to work. mySIMBL does need SIP to be disabled once to install a file in a system folder but once that's done plugins can be managed with SIP on or off.

**Comment by mrtgrizzly** [comment]
Thanks for this extra confirmation and the steps to take.

When I get up the courage to monkey with the iMac, I'll give it a whirl and take the steps.  I am really not keen on the finder sidebar interface.  I get the aesthetics of minimalism and the beauty of monochrome, but in this situation, I want my little icons and colors back !

Cheers
